audino/backend/routes/projects.py
Added protections to ensure that the label_type table is filled out fully before creating a label
=> Added protections to creating labels

audino/backend/routes/users.py, audino/frontend/src/containers/forms/deleteUser.js, audino/frontend/src/containers/modal.js, audino/frontend/src/pages/admin.js
Added new delete api call to delete users from the admin portal. This allows admins to delete anyone but themselves (to avoid that weird edge case). This branch can be used as a modal for creating the rest of the api-backend calls to be added
=> Added Delete User to Admin Portal

audino/frontend/Dockerfile, audino/frontend/src/components/navbutton.js, audino/frontend/src/pages/annotate.js, audino/frontend/test.sh
Fixed: 
- Bug where when clicking force next, code is unable to call the method `handleNextClip()` as it is a const variable in NavButtons
Solution: 
- Remake NavButtons into a class so the method can be called
- React Production build of frontend does now updates to newest changes
Added: 
- Forced previous button
- Swap between forced previous and forced next depending on what buttons users presses
Closes #119 
Closes #107
=> Hotfix: Fixed bug with force next/previous + frontend production build fixes

audino/frontend/src/components/alert.js, audino/frontend/src/pages/annotate.js
- Moved previous and next buttons on the annotation page so that they are side-by-side instead of on top of each other
=> Fix previous and next button UI

audino/backend/routes/users.py
Fixed:
- Checks to see if the suggest role_id for a new user was part of a hardcoded list [1,2]. This check was replaced by a query to the role table to get all the ids in that table. This makes the function more saleable if we ever add more users in the future
- Deleted a request for a role_id in the delete function. No need to assign a role_id to user if deleting the user
Test: 
- Create new users both via admin portal and sign up page, update that user's role, and then delete user without errors or unexpected events. 
Closes (#133)
=> Remove users.py hardcoding

audino/backend/routes/current_user.py
I forgot to replace a variable with a new variable name I gave it
=> Fix get next button issue

audino/backend/models.py, audino/backend/routes/JsonLabelsToCsv.py, audino/backend/routes/data.py, audino/backend/routes/projects.py, audino/docs/tutorials/upload-data.md, audino/examples/upload_data/upload_data.py, audino/examples/upload_data/upload_mass.py, audino/frontend/src/containers/forms/featureForm.js, audino/frontend/src/pages/annotate.js, audino/frontend/src/pages/annotateHelpers/wavesurferMethods.js, audino/frontend/src/wavesurfer.js/src/drawer.js, audino/frontend/src/wavesurfer.js/src/plugin/regions/index.js, audino/frontend/src/wavesurfer.js/src/plugin/regions/region.js
Allows users to create bounding boxes to annotate both time and frequency locations of bird calls in the audio files. 
This requires further testing to make sure it is working successfully. Merge this with a late-summer release.
=> Turned regions into bounding boxes -(wait for feature toggle till merge)

audino/backend/routes/projects.py
Added a call to get all labelTypes
=> Added call to get labelTypes from labelTypes table

audino/frontend/src/containers/forms/featureForm.js, audino/frontend/src/pages/annotate.js
added to feature form, playback changer changes the speed at which the audio file plays at
closes #49
=> Added  playback changer

audino/backend/models.py, audino/backend/routes/projects.py, audino/frontend/src/containers/forms/editProjectForm.js, audino/frontend/src/pages/annotate.js
Todo:
Make sure new users get into a set example branch and make sure the user can always uncheck it
=> Fixed example project bug

audino/backend/routes/users.py, audino/frontend/src/containers/forms/deleteUser.js, audino/frontend/src/pages/admin.js, audino/frontend/src/pages/annotate.js
Now able to delete other users than yourself without worrying about 404 errors
=> fixed issue where user did not update when deleted

audino/frontend/src/components/annotate/extraFeatures/next_unsaved_button.js, audino/frontend/src/components/dump.txt, audino/frontend/src/components/reference.js, audino/frontend/src/containers/forms/featureForm.js, audino/frontend/src/containers/forms/uploadDataForm.js, audino/frontend/src/css/index.css, audino/frontend/src/pages/admin.js, audino/frontend/src/pages/annotate.js
Updated some linting and spelling errors in the code.
=> Spelling and linting fixes 

audino/frontend/src/containers/forms/featureForm.js, audino/frontend/src/pages/annotate.js, audino/frontend/src/pages/annotateHelpers/wavesurferMethods.js, audino/frontend/src/wavesurfer.js/src/plugin/spectrogram/index.js, audino/frontend/src/wavesurfer.js/src/plugin/spectrogram/spectrogram.js
Now with feature form
Basically enabled feature to invert spectrogram, might add some other cooler features now that I have this power
Closes #161
=> Spectrogram changer 

audino/frontend/src/pages/data.js
As user scrolls down on data page, more audio files appear
TODO:
- ~~Add point at end of doc to note end of data~~
- ~~Add a loader to make it clear to user data is loading as they scroll~~
- ~~rebase with refractor~~
Test: scroll down height, let data load over time
Check to make sure data doesn't repeat
=> Infinite data scroll

audino/frontend/src/components/annotate/extraFeatures/next_unsaved_button.js
this.setState broke because I never treated the class like a proper react component so I replaced with this.state = {}. 
Test:
- Make a region
- See count increment
- delete region
- see count decrement
- Play around some more by clicking button and adding in more regions
Closes #193
=> Fixed toUnsaved Button

audino/backend/routes/next_clip.py, audino/frontend/src/pages/dashboard.js
-basically
previous annotation pages are reset when you quick-start
Give random recommendations and recommend clips you did not annotate
=> Various bug fixes

audino/backend/models.py, audino/backend/routes/data.py, audino/backend/routes/projects.py, audino/frontend/package.json
Test:
Have 2 user accounts annotate the same region/segment
Download json, check if both users are in last_modified_by section
=> Allow muiple users to be added to list in last_modified_by in json download

audino/frontend/src/components/reference.js, audino/frontend/src/wavesurfer.js/src/plugin/spectrogram/spectrogram.js, audino/frontend/src/wavesurfer.js/src/webaudio.js
Fixed bug that prevented Firefox from loading spectrograms.
Test:
- Get newest release of firefox
- Log into local pyrenote build
- annotate a clip
- get annotations
There should be no bugs
=> Added Firefox combability changes

audino/backend/routes/data.py, audino/backend/routes/helper_functions.py, audino/frontend/src/containers/forms/uploadDataForm.js
Adds in update to file upload to authenticate upload with jwt token
=> Hotfix v1.2.1

audino/backend/routes/__init__.py, audino/backend/routes/helper_functions.py, audino/backend/routes/labels.py, audino/frontend/src/containers/forms/createLabelValuelForm.js
Create labels from 1 column csv file
Closes: #219
=> Label file upload

README.md, audino/frontend/src/pages/dashboard.js, github_procedures.md
Fixed typo in the quick start buttons on the dashboard page
Updated README.md and github_procedures.md with latest pipelines and data.
=> Typos and readme updates

audino/backend/models.py, audino/backend/routes/__init__.py, audino/backend/routes/current_user.py, audino/backend/routes/projects.py, audino/frontend/package.json, audino/frontend/src/components/button.js, audino/frontend/src/containers/forms/deleteProject.js, audino/frontend/src/containers/forms/recoverProject.js, audino/frontend/src/containers/modal.js, audino/frontend/src/css/index.css, audino/frontend/src/pages/admin.js, audino/frontend/src/pages/adminHandleForm.js
1.  Added a column of checkboxes in the "**Projects**" section of  "**Admin Panel**" tab. The checkbox in the header row has a "**Select/Deselect All**"  which will select and deselect all checkboxes. This checkbox will also be checked if you check all the checkboxes individually without using the "**Select All**" functionality. This checkbox will also be unchecked if not all checkboxes are checked. 
2.  Added a colored icon next to the text **"Projects"** in the "**Projects**" section of  "**Admin Panel**" tab to show if the projects displayed are either the current projects or removed projects. **"Current"** is the default text shown. **"Removed"** will be shown if the trashcan icon is clicked.
3. Added 3 icons (trashcan,  exit trashcan, remove, recover). The trashcan icon upon clicking …
=> Implemented feature for admin role users to remove and recover projects.

audino/backend/routes/JsonLabelsToCsv.py, audino/frontend/src/containers/forms/createUserForm.js, audino/frontend/src/containers/forms/editUserForm.js, audino/frontend/src/pages/data.js
- Users can no longer create usernames with a comma
- In CSV output, added the original created user and split last modified time and user into two separate columns
=> Fix csv formatting errors

audino/frontend/src/components/annotate/toggleYesNo.js, audino/frontend/src/pages/annotate.js
Resolved Issues
#293 
- Next button on annotation page is the default
#294 
- Default "yes" on confident labeling
=> Default button features
